name: build
on:
  push:
    branches:
      - main
jobs:
  deploy:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      
      - name: Build
        uses: jakejarvis/hugo-build-action@master
